dist: trusty
sudo: false
language: rust

env:
  global:
    - PROJECT_NAME=pretty-git-prompt

rust:
  - stable
  - nightly

# matrix:
#   allow_failures:
#     - rust: nightly
# 
# before_install:
#   - sudo apt-get update
#   - sudo apt-get upgrade -y cmake
