[package]
name = "pretty-git-prompt"
version = "0.0.1"
authors = ["Tomas Tomecek <tomas@tomecek.net>"]

[[bin]]
bench = false
path = "src/main.rs"
name = "pretty-git-prompt"

[dependencies]
yaml-rust = "0.3.4"

[dependencies.clap]
version = "2.19"
default-features = false

[dependencies.git2]
version = "0.6"
default-features = false
features = []
